name: Maintenance

on:
  schedule:
    # At 12:00 on Mondays
    - cron:  '0 12 * * 1'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '12' ]
    steps:
    - uses: actions/checkout@v1
    - run: npm i
    - name: Create issue if tests fail
      run: |
        npm t || curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Automated issue for failing periodic tests",
          "body": "This issue is automatically created.\n - workflow `${{ github.workflow }}`\n - commit #${{ github.sha }}",
          "assignee": "omrilotan"
          }'
